# Generated by `aibox` — do NOT edit. Re-run `aibox theme` to refresh.
# Exports keep ANSI-colored tools (bat, delta, fzf, eza, less) aligned with
# the active aibox theme.

export BAT_THEME="Coldark-Dark"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:-} --color=bg+:#313244,bg:#1F1F28,fg:#DCD7BA,fg+:#DCD7BA,hl:#7E9CD8,hl+:#7E9CD8,pointer:#7E9CD8,marker:#98BB6C,spinner:#7E9CD8,info:#727169,header:#727169,border:#727169,prompt:#7E9CD8,query:#DCD7BA,disabled:#727169,gutter:#1F1F28,preview-bg:#1F1F28,preview-fg:#DCD7BA,separator:#727169,label:#7E9CD8"
export EZA_COLORS="di=38;2;126;156;216;1:ex=38;2;152;187;108:ln=38;2;122;168;159:fi=0:or=38;2;195;64;67:mi=38;2;195;64;67:da=38;2;114;113;105:sn=38;2;126;156;216:sb=38;2;126;156;216:uu=38;2;114;113;105:un=38;2;114;113;105:gu=38;2;114;113;105:gn=38;2;114;113;105:ga=38;2;152;187;108:gm=38;2;255;158;59:gd=38;2;195;64;67:gv=38;2;255;158;59:gt=38;2;210;126;153:xx=38;2;114;113;105:da=38;2;114;113;105"

# `less` headings / search hits — match prompt accent / warnings.
export LESS_TERMCAP_md=$'\e[38;2;126;156;216m'    # bold (section headers, command names)
export LESS_TERMCAP_us=$'\e[38;2;255;158;59m'    # underline (options, args)
export LESS_TERMCAP_so=$'\e[38;2;126;156;216;7m'  # reverse (search / status line)
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export GROFF_NO_SGR=1                  # tell groff to emit ANSI, not SGR-bypass
unset LESS_TERMCAP_mb || true
# Keep an obvious error color available for tools that look for $AIBOX_ERROR_COLOR.
export AIBOX_ERROR_SGR='38;2;195;64;67'
