" aibox.vim — generated by aibox CLI from the active theme palette.
" Do NOT edit; re-run `aibox theme` to regenerate.

hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "aibox"
set background=dark

" ── UI chrome ──────────────────────────────────────────────────────────────
hi Normal         guifg=#DCD7BA     guibg=#1F1F28     ctermfg=NONE ctermbg=NONE
hi NormalNC       guifg=#DCD7BA     guibg=#1F1F28
hi LineNr         guifg=#727169  guibg=#1F1F28
hi CursorLineNr   guifg=#7E9CD8 guibg=#313244 gui=bold
hi CursorLine     guibg=#313244
hi CursorColumn   guibg=#313244
hi ColorColumn    guibg=#313244
hi VertSplit      guifg=#727169  guibg=#1F1F28
hi WinSeparator   guifg=#727169  guibg=#1F1F28
hi StatusLine     guifg=#1F1F28     guibg=#7E9CD8 gui=bold
hi StatusLineNC   guifg=#727169  guibg=#313244
hi TabLine        guifg=#727169  guibg=#313244
hi TabLineFill    guibg=#1F1F28
hi TabLineSel     guifg=#1F1F28     guibg=#7E9CD8 gui=bold
hi SignColumn     guifg=#727169  guibg=#1F1F28
hi FoldColumn     guifg=#727169  guibg=#1F1F28
hi Folded         guifg=#727169  guibg=#313244
hi NonText        guifg=#727169
hi EndOfBuffer    guifg=#1F1F28     guibg=#1F1F28
hi SpecialKey     guifg=#727169
hi MatchParen     guifg=#7E9CD8 guibg=#313244 gui=bold,underline
hi Conceal        guifg=#727169  guibg=#1F1F28
hi Directory      guifg=#7E9CD8 gui=bold

" ── Selection / search ────────────────────────────────────────────────────
hi Visual         guibg=#313244
hi VisualNOS      guibg=#313244
hi Search         guifg=#1F1F28     guibg=#FF9E3B gui=bold
hi IncSearch      guifg=#1F1F28     guibg=#D27E99 gui=bold
hi CurSearch      guifg=#1F1F28     guibg=#7E9CD8 gui=bold
hi QuickFixLine   guibg=#313244 gui=bold

" ── Popup menu ────────────────────────────────────────────────────────────
hi Pmenu          guifg=#DCD7BA     guibg=#313244
hi PmenuSel       guifg=#1F1F28     guibg=#7E9CD8 gui=bold
hi PmenuSbar      guibg=#313244
hi PmenuThumb     guibg=#727169
hi WildMenu       guifg=#1F1F28     guibg=#7E9CD8 gui=bold

" ── Messages ──────────────────────────────────────────────────────────────
hi ErrorMsg       guifg=#C34043    gui=bold
hi WarningMsg     guifg=#FF9E3B
hi ModeMsg        guifg=#7E9CD8 gui=bold
hi MoreMsg        guifg=#98BB6C
hi Question       guifg=#7E9CD8
hi Title          guifg=#7E9CD8 gui=bold

" ── Syntax (linked groups) ────────────────────────────────────────────────
hi Comment        guifg=#727169    gui=italic
hi Constant       guifg=#D27E99
hi String         guifg=#98BB6C
hi Character      guifg=#98BB6C
hi Number         guifg=#D27E99
hi Boolean        guifg=#D27E99
hi Float          guifg=#D27E99
hi Identifier     guifg=#DCD7BA
hi Function       guifg=#7E9CD8
hi Statement      guifg=#C34043
hi Conditional    guifg=#C34043
hi Repeat         guifg=#C34043
hi Label          guifg=#FF9E3B
hi Operator       guifg=#7AA89F
hi Keyword        guifg=#C34043
hi Exception      guifg=#C34043
hi PreProc        guifg=#FF9E3B
hi Include        guifg=#C34043
hi Define         guifg=#C34043
hi Macro          guifg=#7E9CD8
hi PreCondit      guifg=#FF9E3B
hi Type           guifg=#FF9E3B
hi StorageClass   guifg=#FF9E3B
hi Structure      guifg=#FF9E3B
hi Typedef        guifg=#FF9E3B
hi Special        guifg=#7AA89F
hi SpecialChar    guifg=#D27E99
hi Tag            guifg=#7E9CD8
hi Delimiter      guifg=#DCD7BA
hi SpecialComment guifg=#727169    gui=italic
hi Debug          guifg=#D27E99
hi Underlined     guifg=#7E9CD8   gui=underline
hi Ignore         guifg=#727169
hi Error          guifg=#C34043      gui=bold
hi Todo           guifg=#FF9E3B   guibg=#313244 gui=bold

" ── Diff ──────────────────────────────────────────────────────────────────
hi DiffAdd        guifg=#98BB6C    guibg=#1F1F28
hi DiffChange     guifg=#FF9E3B   guibg=#1F1F28
hi DiffDelete     guifg=#C34043      guibg=#1F1F28
hi DiffText       guifg=#7E9CD8   guibg=#1F1F28    gui=bold
hi diffAdded      guifg=#98BB6C
hi diffRemoved    guifg=#C34043
hi diffChanged    guifg=#FF9E3B
hi diffFile       guifg=#7E9CD8   gui=bold
hi diffNewFile    guifg=#98BB6C    gui=bold
hi diffOldFile    guifg=#C34043      gui=bold
hi diffLine       guifg=#727169

" ── Spelling ──────────────────────────────────────────────────────────────
hi SpellBad       gui=undercurl guisp=#C34043
hi SpellCap       gui=undercurl guisp=#FF9E3B
hi SpellLocal     gui=undercurl guisp=#7AA89F
hi SpellRare      gui=undercurl guisp=#A7647E

" ── Git plugins / gitgutter / signify ────────────────────────────────────
hi GitGutterAdd          guifg=#98BB6C    guibg=#1F1F28
hi GitGutterChange       guifg=#FF9E3B   guibg=#1F1F28
hi GitGutterDelete       guifg=#C34043      guibg=#1F1F28
hi GitGutterChangeDelete guifg=#D27E99   guibg=#1F1F28
hi SignifySignAdd        guifg=#98BB6C    guibg=#1F1F28
hi SignifySignChange     guifg=#FF9E3B   guibg=#1F1F28
hi SignifySignDelete     guifg=#C34043      guibg=#1F1F28

" ── Markdown ──────────────────────────────────────────────────────────────
hi link markdownH1        Title
hi link markdownH2        Title
hi link markdownH3        Title
hi link markdownH4        Title
hi link markdownCode      String
hi link markdownCodeBlock String
hi link markdownLinkText  Function
hi markdownUrl   guifg=#7AA89F  gui=underline

" ── Vim help ──────────────────────────────────────────────────────────────
hi link helpHyperTextEntry Underlined
hi link helpHyperTextJump  Underlined
hi link helpHeader         Title
hi link helpExample        String
hi link helpOption         Type
hi link helpVim            Identifier

" ── Misc plugins ──────────────────────────────────────────────────────────
hi link NvimTreeFolderName Directory
hi link NvimTreeRootFolder Title
hi link TelescopeBorder    FloatBorder
hi FloatBorder    guifg=#727169    guibg=#1F1F28
hi NormalFloat    guifg=#DCD7BA       guibg=#313244
