[module]
  [[module.mounts]]
    source = "src/archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "src/assets"
    target = "assets"
  [[module.mounts]]
    source = "src/i18n"
    target = "i18n"
  [[module.mounts]]
    source = "src/layouts"
    target = "layouts"
  [[module.mounts]]
    source = "src/static"
    target = "static"
