gui:
  theme:
    activeBorderColor:
      - '#7E9CD8'
      - bold
    inactiveBorderColor:
      - '#938AA9'
    optionsTextColor:
      - '#7AA89F'
    selectedLineBgColor:
      - '#3F4A64'
    cherryPickedCommitBgColor:
      - '#938AA9'
    cherryPickedCommitFgColor:
      - '#7E9CD8'
    unstagedChangesColor:
      - '#E46876'
    defaultFgColor:
      - '#DCD7BA'
    searchingActiveBorderColor:
      - '#E6C384'
      - bold
