# Generated by `aibox` — do NOT edit. Re-run `aibox theme` to refresh.
# Exports keep ANSI-colored tools (bat, delta, fzf, eza, less) aligned with
# the active aibox theme.

export BAT_THEME="aibox"
# Bat indexes custom TextMate themes into its cache. Rebuild only when the
# generated aibox theme is not present (normally once after apply/theme switch).
if command -v bat >/dev/null 2>&1 && ! bat --list-themes 2>/dev/null | grep -qx 'aibox'; then
    bat cache --build >/dev/null 2>&1 || true
fi
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:-} --color=bg+:#3F4A64,bg:#1F1F28,fg:#DCD7BA,fg+:#FFFFFF:bold,hl:#7E9CD8,hl+:#7E9CD8:bold,pointer:#7E9CD8,marker:#98BB6C,spinner:#7E9CD8,info:#938AA9,header:#938AA9,border:#938AA9,prompt:#7E9CD8:bold,query:#DCD7BA,disabled:#938AA9:dim,gutter:#1F1F28,preview-bg:#1F1F28,preview-fg:#DCD7BA,separator:#938AA9,label:#7E9CD8"
export EZA_COLORS="di=38;2;126;156;216;1:ex=38;2;152;187;108:ln=38;2;122;168;159:fi=0:or=38;2;228;104;118;1:mi=38;2;228;104;118;1:da=38;2;147;138;169;2:sn=38;2;126;156;216:sb=38;2;126;156;216:uu=38;2;147;138;169:un=38;2;147;138;169:gu=38;2;147;138;169:gn=38;2;147;138;169:ga=38;2;152;187;108;1:gm=38;2;230;195;132;1:gd=38;2;228;104;118;1:gv=38;2;230;195;132:gt=38;2;255;160;102;3:xx=38;2;147;138;169;2:da=38;2;147;138;169;2"

# `less` headings / search hits — match prompt accent / warnings.
export LESS_TERMCAP_md=$'\e[38;2;126;156;216;1m'    # section headers, command names
export LESS_TERMCAP_us=$'\e[38;2;230;195;132;4m'    # options, args
export LESS_TERMCAP_so=$'\e[38;2;126;156;216;7m'  # search / status line
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export GROFF_NO_SGR=1                  # tell groff to emit ANSI, not SGR-bypass
unset LESS_TERMCAP_mb || true
# Keep an obvious error color available for tools that look for $AIBOX_ERROR_COLOR.
export AIBOX_ERROR_SGR='38;2;228;104;118'
