#!/usr/bin/env bash
# tmux-powerkit theme — generated by aibox CLI from the active theme palette.
# Loaded via @powerkit_theme "custom" + @powerkit_custom_theme_path.
# Do NOT edit; re-run `aibox theme` to regenerate.

declare -gA THEME_COLORS=(
    # Core
    [background]="#1F1F28"

    # Status bar
    [statusbar-bg]="#2E2E34"
    [statusbar-fg]="#DCD7BA"

    # Session (status-left)
    [session-bg]="#7E9CD8"
    [session-fg]="#000000"
    [session-prefix-bg]="#E46876"
    [session-copy-bg]="#7AA89F"
    [session-search-bg]="#E6C384"
    [session-command-bg]="#957FB8"

    # Windows
    [window-active-base]="#7E9CD8"
    [window-active-style]="bold"
    [window-inactive-base]="#938AA9"
    [window-inactive-style]="dim"
    [window-activity-style]="dim"
    [window-bell-style]="bold"
    [window-zoomed-bg]="#7AA89F"

    # Panes
    [pane-border-active]="#7E9CD8"
    [pane-border-inactive]="#938AA9"

    # Health / state segments (chevron color rotation source)
    [ok-base]="#8B90B9"
    [good-base]="#98BB6C"
    [info-base]="#7AA89F"
    [warning-base]="#E6C384"
    [error-base]="#E46876"
    [disabled-base]="#938AA9"

    # Messages
    [message-bg]="#2E2E34"
    [message-fg]="#DCD7BA"

    # Popup & menu
    [popup-bg]="#2E2E34"
    [popup-fg]="#DCD7BA"
    [popup-border]="#7E9CD8"
    [menu-bg]="#2E2E34"
    [menu-fg]="#DCD7BA"
    [menu-selected-bg]="#7E9CD8"
    [menu-selected-fg]="#000000"
    [menu-border]="#7E9CD8"
)

# Extra slots some plugins read directly — also derived from the palette so
# every chevron lands on a known-good bg.
declare -gA THEME_EXTRA=(
    [orange]="#FFA066"
    [magenta]="#957FB8"
    [surface]="#2E2E34"
)
