direction: right

internet: Internet {
  shape: cloud
}

aws: AWS account {
  icon: https://icons.d2lang.com/aws%2F_Group%20Icons%2FAWS-Cloud-alt_light-bg.svg
  style: {
    stroke: "#d86613"
    font-color: "#8a3b00"
    fill: white
  }

  region: eu-central-1 {
    vpc: Production VPC 10.1.0.0/16 {
      icon: https://icons.d2lang.com/aws%2F_Group%20Icons%2FVirtual-private-cloud-VPC_light-bg.svg
      style: {
        stroke: green
        font-color: green
        fill: white
      }

      az-a: Availability Zone A {
        style: {
          stroke: blue
          font-color: blue
          stroke-dash: 3
          fill: white
        }

        public: Public subnet {
          lb: Application Load Balancer
        }

        private: Private subnet {
          lambda: Lambda API {
            icon: https://icons.d2lang.com/aws/Compute/AWS-Lambda.svg
          }
        }

        data: Database subnet {
          db: Amazon RDS PostgreSQL {
            icon: https://icons.d2lang.com/aws%2FDatabase%2FAmazon-RDS_light-bg.svg
          }
        }
      }
    }
  }
}

internet -> aws.region.vpc.az-a.public.lb: HTTPS
aws.region.vpc.az-a.public.lb -> aws.region.vpc.az-a.private.lambda
aws.region.vpc.az-a.private.lambda -> aws.region.vpc.az-a.data.db
