#!/usr/bin/env bash
# tmux-powerkit theme — generated by aibox CLI from the active theme palette.
# Loaded via @powerkit_theme "custom" + @powerkit_custom_theme_path.
# Do NOT edit; re-run `aibox theme` to regenerate.

declare -gA THEME_COLORS=(
    # Core
    [background]="#1F1F28"

    # Status bar
    [statusbar-bg]="#313244"
    [statusbar-fg]="#DCD7BA"

    # Session (status-left)
    [session-bg]="#7E9CD8"
    [session-fg]="#1F1F28"
    [session-prefix-bg]="#C34043"
    [session-copy-bg]="#7AA89F"
    [session-search-bg]="#FF9E3B"
    [session-command-bg]="#A7647E"

    # Windows
    [window-active-base]="#7E9CD8"
    [window-active-style]="bold"
    [window-inactive-base]="#727169"
    [window-inactive-style]="none"
    [window-activity-style]="italics"
    [window-bell-style]="bold"
    [window-zoomed-bg]="#7AA89F"

    # Panes
    [pane-border-active]="#7E9CD8"
    [pane-border-inactive]="#727169"

    # Health / state segments (chevron color rotation source)
    [ok-base]="#76808F"
    [good-base]="#98BB6C"
    [info-base]="#7AA89F"
    [warning-base]="#FF9E3B"
    [error-base]="#C34043"
    [disabled-base]="#727169"

    # Messages
    [message-bg]="#313244"
    [message-fg]="#DCD7BA"

    # Popup & menu
    [popup-bg]="#313244"
    [popup-fg]="#DCD7BA"
    [popup-border]="#7E9CD8"
    [menu-bg]="#313244"
    [menu-fg]="#DCD7BA"
    [menu-selected-bg]="#7E9CD8"
    [menu-selected-fg]="#1F1F28"
    [menu-border]="#7E9CD8"
)

# Extra slots some plugins read directly — also derived from the palette so
# every chevron lands on a known-good bg.
declare -gA THEME_EXTRA=(
    [orange]="#D27E99"
    [magenta]="#A7647E"
    [surface]="#313244"
)
