[security.exec]
  allow = ["^(dart-)?sass$", "^go$", "^git$", "^node$", "^postcss$", "^tailwindcss$"]

[params]
  [[params.versions]]
    label = "v0.3.4"
    url = "https://projectious-work.github.io/brand-theme-hugo-vanilla/"
    note = "latest"
  [[params.versions]]
    label = "v0.3.3"
    url = "https://projectious-work.github.io/brand-theme-hugo-vanilla/v0.3.3/"
  [[params.versions]]
    label = "v0.3.2"
    url = "https://projectious-work.github.io/brand-theme-hugo-vanilla/v0.3.2/"
  [[params.versions]]
    label = "v0.3.1"
    url = "https://projectious-work.github.io/brand-theme-hugo-vanilla/v0.3.1/"
