" aibox.vim — generated by aibox CLI from the active theme palette.
" Do NOT edit; re-run `aibox theme` to regenerate.

hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "aibox"
set background=dark

" ── UI chrome ──────────────────────────────────────────────────────────────
hi Normal         guifg=#DCD7BA     guibg=#1F1F28     ctermfg=NONE ctermbg=NONE
hi NormalNC       guifg=#DCD7BA     guibg=#1F1F28
hi Cursor         guifg=#000000 guibg=#7E9CD8
hi lCursor        guifg=#000000 guibg=#7E9CD8
hi LineNr         guifg=#938AA9  guibg=#1F1F28
hi CursorLineNr   guifg=#7E9CD8 guibg=#2E2E34 gui=bold
hi CursorLine     guibg=#2E2E34
hi CursorColumn   guibg=#2E2E34
hi ColorColumn    guibg=#2E2E34
hi VertSplit      guifg=#938AA9  guibg=#1F1F28
hi WinSeparator   guifg=#938AA9  guibg=#1F1F28
hi StatusLine     guifg=#000000 guibg=#7E9CD8 gui=bold
hi StatusLineNC   guifg=#938AA9  guibg=#2E2E34 gui=NONE
hi TabLine        guifg=#938AA9  guibg=#2E2E34 gui=NONE
hi TabLineFill    guibg=#1F1F28
hi TabLineSel     guifg=#000000 guibg=#7E9CD8 gui=bold
hi SignColumn     guifg=#938AA9  guibg=#1F1F28
hi FoldColumn     guifg=#938AA9  guibg=#1F1F28
hi Folded         guifg=#938AA9  guibg=#2E2E34
hi NonText        guifg=#938AA9
hi EndOfBuffer    guifg=#1F1F28     guibg=#1F1F28
hi SpecialKey     guifg=#938AA9
hi MatchParen     guifg=#7E9CD8 guibg=#2E2E34 gui=bold
hi Conceal        guifg=#938AA9  guibg=#1F1F28
hi Directory      guifg=#7E9CD8 gui=bold

" ── Selection / search ────────────────────────────────────────────────────
hi Visual         guifg=#FFFFFF guibg=#3F4A64
hi VisualNOS      guifg=#FFFFFF guibg=#3F4A64
hi Search         guifg=#1F1F28     guibg=#E6C384 gui=bold
hi IncSearch      guifg=#1F1F28     guibg=#FFA066 gui=bold
hi CurSearch      guifg=#000000 guibg=#7E9CD8 gui=bold
hi QuickFixLine   guibg=#2E2E34 gui=bold

" ── Popup menu ────────────────────────────────────────────────────────────
hi Pmenu          guifg=#DCD7BA     guibg=#2E2E34
hi PmenuSel       guifg=#000000 guibg=#7E9CD8 gui=bold
hi PmenuSbar      guibg=#2E2E34
hi PmenuThumb     guibg=#938AA9
hi WildMenu       guifg=#000000 guibg=#7E9CD8 gui=bold

" ── Messages ──────────────────────────────────────────────────────────────
hi ErrorMsg       guifg=#E46876    gui=bold
hi WarningMsg     guifg=#E6C384 gui=bold
hi ModeMsg        guifg=#7E9CD8 gui=bold
hi MoreMsg        guifg=#98BB6C
hi Question       guifg=#7E9CD8
hi Title          guifg=#7E9CD8 gui=bold

" ── Syntax (linked groups) ────────────────────────────────────────────────
hi Comment        guifg=#938AA9    gui=italic
hi Constant       guifg=#FFA066
hi String         guifg=#98BB6C     gui=NONE
hi Character      guifg=#98BB6C     gui=NONE
hi Number         guifg=#FFA066    gui=NONE
hi Boolean        guifg=#FFA066    gui=NONE
hi Float          guifg=#FFA066    gui=NONE
hi Identifier     guifg=#DCD7BA
hi Function       guifg=#7AA89F      gui=NONE
hi Statement      guifg=#957FB8  gui=bold
hi Conditional    guifg=#957FB8  gui=bold
hi Repeat         guifg=#957FB8  gui=bold
hi Label          guifg=#E6C384
hi Operator       guifg=#7AA89F      gui=NONE
hi Keyword        guifg=#957FB8  gui=bold
hi Exception      guifg=#957FB8  gui=bold
hi PreProc        guifg=#957FB8
hi Include        guifg=#957FB8
hi Define         guifg=#957FB8
hi Macro          guifg=#7E9CD8   gui=italic
hi PreCondit      guifg=#E6C384
hi Type           guifg=#E6C384   gui=bold
hi StorageClass   guifg=#E6C384   gui=bold
hi Structure      guifg=#E6C384   gui=bold
hi Typedef        guifg=#E6C384   gui=bold
hi Special        guifg=#7AA89F
hi SpecialChar    guifg=#FFA066
hi Tag            guifg=#7E9CD8
hi Delimiter      guifg=#DCD7BA
hi SpecialComment guifg=#938AA9    gui=italic
hi Debug          guifg=#FFA066
hi Underlined     guifg=#7E9CD8   gui=underline
hi Ignore         guifg=#938AA9
hi Error          guifg=#E46876      gui=bold
hi Todo           guifg=#E6C384   guibg=#2E2E34 gui=bold

" ── Diff ──────────────────────────────────────────────────────────────────
hi DiffAdd        guifg=#98BB6C    guibg=#3A4137
hi DiffChange     guifg=#E6C384   guibg=#4B433C
hi DiffDelete     guifg=#E46876      guibg=#4A2F39
hi DiffText       guifg=#7E9CD8   guibg=#4B433C gui=bold
hi diffAdded      guifg=#98BB6C
hi diffRemoved    guifg=#E46876
hi diffChanged    guifg=#E6C384
hi diffFile       guifg=#7E9CD8   gui=bold
hi diffNewFile    guifg=#98BB6C    gui=bold
hi diffOldFile    guifg=#E46876      gui=bold
hi diffLine       guifg=#938AA9

" ── Spelling ──────────────────────────────────────────────────────────────
hi SpellBad       gui=undercurl guisp=#E46876
hi SpellCap       gui=undercurl guisp=#E6C384
hi SpellLocal     gui=undercurl guisp=#7AA89F
hi SpellRare      gui=undercurl guisp=#957FB8

" ── Git plugins / gitgutter / signify ────────────────────────────────────
hi GitGutterAdd          guifg=#98BB6C    guibg=#1F1F28
hi GitGutterChange       guifg=#E6C384   guibg=#1F1F28
hi GitGutterDelete       guifg=#E46876      guibg=#1F1F28
hi GitGutterChangeDelete guifg=#FFA066   guibg=#1F1F28
hi SignifySignAdd        guifg=#98BB6C    guibg=#1F1F28
hi SignifySignChange     guifg=#E6C384   guibg=#1F1F28
hi SignifySignDelete     guifg=#E46876      guibg=#1F1F28

" ── Markdown ──────────────────────────────────────────────────────────────
hi link markdownH1        Title
hi link markdownH2        Title
hi link markdownH3        Title
hi link markdownH4        Title
hi link markdownCode      String
hi link markdownCodeBlock String
hi link markdownLinkText  Function
hi markdownUrl   guifg=#7AA89F  gui=underline

" ── Vim help ──────────────────────────────────────────────────────────────
hi link helpHyperTextEntry Underlined
hi link helpHyperTextJump  Underlined
hi link helpHeader         Title
hi link helpExample        String
hi link helpOption         Type
hi link helpVim            Identifier

" ── Misc plugins ──────────────────────────────────────────────────────────
hi link NvimTreeFolderName Directory
hi link NvimTreeRootFolder Title
hi link TelescopeBorder    FloatBorder
hi FloatBorder    guifg=#938AA9    guibg=#1F1F28
hi NormalFloat    guifg=#DCD7BA       guibg=#2E2E34
